# Generated by Django 4.1.7 on 2023-03-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, choices=[('2024', '2024'), ('2023', '2023'), ('2025', '2025'), ('2026', '2026')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('pdfLink', models.CharField(blank=True, max_length=200, null=True)),
                ('ytlink', models.CharField(blank=True, max_length=200, null=True)),
                ('members', models.ManyToManyField(blank=True, null=True, to='src.team_member')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.CharField(blank=True, choices=[('Structural', 'Structural'), ('Electronice', 'Electronics'), ('Coding', 'Coding')], max_length=200, null=True)),
                ('year', models.CharField(blank=True, choices=[('2024', '2024'), ('2023', '2023'), ('2025', '2025'), ('2026', '2026')], max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedinLInk', models.CharField(blank=True, max_length=200, null=True)),
                ('githubLink', models.CharField(blank=True, max_length=200, null=True)),
                ('twitterLink', models.CharField(blank=True, max_length=200, null=True)),
                ('projects_part', models.ManyToManyField(blank=True, null=True, to='src.projects')),
            ],
        ),
    ]
