# Generated by Django 4.1.7 on 2023-03-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
